clear all
disp('15PSI')
tic
parameter_calc('15PSI','PRE');
toc
disp('20PSI')
parameter_calc('20PSI','PRE');
toc
disp('25PSI')
parameter_calc('25PSI','PRE');
toc
disp('AIRE3_5')
parameter_calc('AIRE3_5','');
toc
disp('AIRE4_5')
parameter_calc('AIRE4_5','');
toc
disp('AIRE5_5')
parameter_calc('AIRE5_5','');
toc
disp('AIRE6_5')
parameter_calc('AIRE6_5','');
toc
disp('AMB')
parameter_calc('AMB','');
toc
disp('HMD')
parameter_calc('HMD','');
toc
disp('HMD58')
parameter_calc('HMD58','');
toc
disp('HMD75')
parameter_calc('HMD75','');
toc
disp('HMD85')
parameter_calc('HMD85','');
toc
disp('T60V')
parameter_calc('T60V','');
toc
disp('T90V')
parameter_calc('T90V','');
toc
disp('T120V')
parameter_calc('T120V','');
toc